[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SENDGRID_FROM_EMAIL,MP_ACCESS_TOKEN,SENDGRID_API_KEY,SHEETS_WEBHOOK_URL"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
